"""
Pedal Trinity - MXR signature (tappa 3B, priorita' B): pedali a scatola con la forma del pedale vero (stomp_layout.py)
e pedali a bilanciere (shaped_layout.py, anche la serie 'Next Step' che oscilla tutta intera), modalita' normale con
nome e sigla ORIGINALI Pedal Trinity e replica REAL MOD con nome e sigla reali del modello (mai il marchio del
produttore). Nessun logo, artwork, ritratto o firma: colori e motivi geometrici semplificati (stomp_textures.py).

Fonti dell'aspetto: schede della tappa 3 (manuali ufficiali, pagine prodotto, misure dei contenitori); le posizioni
dei comandi (x%, y% sul piano visto dall'alto) sono in gran parte stime +-5-8 punti, le misure con est=True stimate.
La parte funzionale viene da sound_stage3b_analog.json / sound_stage3b_digital.json (stomp_catalog.stomp/rocker): i
comandi qui sotto sono il segnaposto usato finche' l'id manca in quei file.
File generato da gen_catalog_b.py (tappa 3B).
"""
from catalog import knob, outer, inner, selector, toggle, slider, button
from stomp_catalog import stomp, look, rocker, treadle_look

MODELS = [
    # MXR KFK1 Kerry King Ten Band EQ - c. 2009-2010 (stima; manuale rev. D 2013)
    stomp("kfk1", "YQ-1", "Tattoo Ten Band", "MXR KFK1 Kerry King Ten Band EQ",
          ("KFK1", "Ten Band EQ"), "Equalizzatori", (24, 24, 26),
          look("mxr_big", (152, 92, 38),
               [('VOLUME', 6, 30, 'slider'), ('31', 16.0, 30, 'slider', ['31,25 Hz']), ('62', 23.6, 30, 'slider', ['62,5 Hz']),
                ('125', 31.2, 30, 'slider', ['125 Hz']), ('250', 38.8, 30, 'slider', ['250 Hz']),
                ('500', 46.4, 30, 'slider', ['500 Hz']), ('1K', 54.0, 30, 'slider', ['1 kHz']),
                ('2K', 61.6, 30, 'slider', ['2 kHz']), ('4K', 69.2, 30, 'slider', ['4 kHz']), ('8K', 76.8, 30, 'slider', ['8 kHz']),
                ('16K', 84.4, 30, 'slider', ['16 kHz (shelving)']), ('GAIN', 94, 30, 'slider')],
               feet=[('ON/OFF', 50, 84)], leds=[], extra=[], finish='paint', gfx={'panels': [('hline', 6, (196, 32, 36), 0.8, 4, 96)],
                'name': {'col': (232, 230, 222), 'font': 'blackit', 'upper': True, 'y': 57.9, 'size': 6.5},
                'label': {'col': (232, 230, 222), 'size': 1.8},
                'name_deco': {'style': 'band', 'col': (150, 22, 26), 'pad': 2.0},
                'code': {'size': 2.6, 'col': (232, 230, 222)}}),
          ("GraphicEQ", [slider("VOLUME", "level", 0.5, 0, 10, "dial"),
            slider("31", "b0", 0.5, -12, 12, "db"),
            slider("62", "b1", 0.5, -12, 12, "db"),
            slider("125", "b2", 0.5, -12, 12, "db"),
            slider("250", "b3", 0.5, -12, 12, "db"),
            slider("500", "b4", 0.5, -12, 12, "db"),
            slider("1K", "b5", 0.5, -12, 12, "db"),
            slider("2K", "b6", 0.5, -12, 12, "db"),
            slider("4K", "b7", 0.5, -12, 12, "db"),
            slider("8K", "b8", 0.5, -12, 12, "db"),
            slider("16K", "b9", 0.5, -12, 12, "db"),
            slider("GAIN", "gain", 0.5, 0, 10, "dial")],
           "freqs=31.25,62.5,125,250,500,1000,2000,4000,8000,16000 qs=1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8 qmin=1.0 range=12 lvl=15"),
          "Equalizzatore grafico a 10 bande a 18 V con doppia uscita: buffer d'ingresso con guadagno, 10 filtri a giratore (op-amp) a +-12 dB, sommatore, volume, doppia uscita. Parte funzionale provvisoria (segnaposto) finche' non arriva la scheda sonora."),

    # MXR EVH Modern High Gain Pedal - 2026 (manuale gennaio 2026; progetto 2015)
    stomp("evhmhg", "YD-2", "Striped High Gain", "MXR EVH Modern High Gain Pedal",
          ("EVHMHG", "Modern High Gain"), "Distorsione", (200, 36, 34),
          look("mxr_big", (92, 121, 38),
               [('OUTPUT', 12, 16, 'knob'), ('BASS', 28, 16, 'knob'), ('BASS SHIFT', 40, 30, 'lever'), ('MID', 54, 16, 'knob'),
                ('TREBLE', 71, 16, 'knob'), ('GAIN', 88, 16, 'knob'), ('GATE', 18, 48, 'knob'), ('BOOST', 80, 48, 'button')],
               feet=[('ON/OFF', 50, 84)], leds=[(66.8, 84, 'red')], extra=[], finish='paint', gfx={'panels': [('stripes', (24, 24, 26), 3.0, 11.0, 32), ('stripes', (232, 230, 222), 1.2, 11.0, -50)],
                'name': {'col': (232, 230, 222), 'font': 'black', 'upper': True, 'y': 64.6, 'size': 6.5},
                'label': {'col': (232, 230, 222)},
                'name_deco': {'style': 'box', 'col': (24, 24, 26), 'pad': 2.0},
                'code': {'size': 2.6, 'col': (232, 230, 222)}}, print='Modern High Gain'),
          ("Circuit", [knob("OUTPUT", "level"),
            knob("BASS", "tone"),
            toggle("BASS SHIFT", "tone", ("55 HZ", "80 HZ"), 0),
            knob("MID", "tone"),
            knob("TREBLE", "tone"),
            knob("GAIN", "gain"),
            knob("GATE", "aux"),
            toggle("BOOST", "gain", ("OFF", "BOOST"), 0)],
           "hpf R=470k C=100n; opni Rg=2.2k Cg=1u Rf=10k+pot(5,470k,A) Cf=100p rail=4; dclip R=2.2k C=10n d=si; tonebm R1=22k C1=10n R2=22k C2=4n t=taper(1,B); vol a=taper(0,A)"),
          "Distorsione ad alto guadagno (progettata con Van Halen nel 2015) con EQ a 3 bande, BASS SHIFT, BOOST e gate: preamp ad alto guadagno multi-stadio con boost sul primo e sull'ultimo stadio, EQ a 3 bande con frequenza dei bassi commutabile, noise gate. Parte funzionale provvisoria (segnaposto) finche' non arriva la scheda sonora."),

    # MXR Custom Shop CSP265 Joe Bonamassa FET Driver - 2013 (manuale novembre 2013)
    stomp("csp265", "YO-4", "Halo FET Drive", "MXR Custom Shop CSP265 Joe Bonamassa FET Driver",
          ("CSP265", "FET Driver"), "Overdrive / Boost", (24, 24, 26),
          look("mxr", (61, 111, 36),
               [('LEVEL', 22, 14, 'knob'), ('DRIVE', 78, 14, 'knob'), ('HI', 36, 36, 'knob'), ('LO', 64, 36, 'knob'),
                ('HI CUT', 50, 24, 'button')],
               feet=[('ON/OFF', 50, 82)], leds=[(50, 52, 'blue'), (50, 30, 'green')], extra=[], finish='paint', gfx={'panels': [('rect', 4, 3, 96, 97, None, (206, 170, 90), 2.5, 0.6)],
                'name': {'col': (206, 170, 90), 'font': 'serif', 'upper': False, 'y': 61.2, 'size': 5.5},
                'label': {'col': (206, 170, 90)},
                'name_deco': {'style': 'lines', 'col': (206, 170, 90), 'pad': 2.0},
                'code': {'size': 2.6, 'col': (206, 170, 90)}}, knob='small'),
          ("Circuit", [knob("LEVEL", "level"),
            knob("DRIVE", "gain"),
            knob("HI", "aux"),
            knob("LO", "aux"),
            toggle("HI CUT", "mode", ("OFF", "HI CUT"), 0)],
           "hpf R=470k C=100n; fbclip Rg=4.7k Cg=47n Rf=10k+pot(1,470k,A) Cf=51p d=si up=1 dn=1 rail=4.2; lpf R=10k C=4.7n; vol a=taper(0,A)"),
          "Overdrive con stadio a operazionale in cascata a uno stadio FET (concetto Tube Driver) e EQ a 2 bande: stadio di guadagno a operazionale -> stadio FET (sostituto della valvola del Tube Driver) -> filtro HI CUT -> EQ attivo HI/LO -> LEVEL. Parte funzionale provvisoria (segnaposto) finche' non arriva la scheda sonora."),

    # MXR TBM1 Tom Morello Power 50 Overdrive - 2022 (manuale dicembre 2021)
    stomp("tbm1", "YO-5", "Red Stencil Fifty", "MXR TBM1 Tom Morello Power 50 Overdrive",
          ("TBM1", "Power 50 Overdrive"), "Overdrive / Boost", (24, 24, 26),
          look("mxr_big", (92, 121, 38),
               [('VOLUME', 12, 16, 'knob'), ('BASS', 31, 16, 'knob'), ('MIDDLE', 50, 16, 'knob'), ('TREBLE', 69, 16, 'knob'),
                ('GAIN', 88, 16, 'knob'), ('PRESENCE', 20, 50, 'knob')],
               feet=[('ON/OFF', 50, 84)], leds=[(50, 64, 'red')], extra=[], finish='matte', gfx={'panels': [],
                'name': {'col': (196, 32, 36), 'font': 'black', 'upper': True, 'spacing': 0.5, 'y': 30.8, 'size': 6.5},
                'label': {'col': (232, 230, 222)},
                'name_deco': {'style': 'lines', 'col': (196, 32, 36), 'pad': 2.0},
                'code': {'size': 2.6, 'col': (232, 230, 222)}}),
          ("Circuit", [knob("VOLUME", "level"),
            knob("BASS", "tone"),
            knob("MIDDLE", "tone"),
            knob("TREBLE", "tone"),
            knob("GAIN", "gain"),
            knob("PRESENCE", "aux")],
           "hpf R=470k C=100n; fbclip Rg=4.7k Cg=47n Rf=10k+pot(4,470k,A) Cf=51p d=si up=1 dn=1 rail=4.2; tonebm R1=22k C1=10n R2=22k C2=4n t=taper(1,B); vol a=taper(0,A)"),
          "Overdrive 'amp in a box' (testata 50 W) con EQ a 3 bande, loop effetti e PRESENCE dopo il loop: preamp con saturazione (GAIN), tone stack BASS/MIDDLE/TREBLE interattivo (tipo amplificatore), VOLUME, mandata/ritorno del loop, stadio 'finale' con PRESENCE. Parte funzionale provvisoria (segnaposto) finche' non arriva la scheda sonora."),

    # MXR EG74 Eric Gales Raw Dawg Overdrive - 2021 (manuale gennaio 2021)
    stomp("eg74", "YO-6", "Lefty Hound Drive", "MXR EG74 Eric Gales Raw Dawg Overdrive",
          ("EG74", "Raw Dawg Overdrive"), "Overdrive / Boost", (34, 44, 92),
          look("mxr", (61, 111, 36),
               [('TONE', 50, 14, 'knob'), ('OUTPUT', 24, 27, 'knob'), ('DRIVE', 76, 27, 'knob')],
               feet=[('KICKSWITCH', 50, 82)], leds=[(50, 40, 'blue')], extra=[], finish='paint', gfx={'panels': [],
                'name': {'col': (24, 24, 26), 'font': 'black', 'upper': True, 'y': 55.2, 'size': 5.5},
                'label': {'col': (232, 230, 222)},
                'name_deco': {'style': 'band', 'col': (230, 180, 60), 'pad': 2.0},
                'code': {'size': 2.6, 'col': (232, 230, 222)}}),
          ("Circuit", [knob("TONE", "tone"),
            knob("OUTPUT", "level"),
            knob("DRIVE", "gain")],
           "hpf R=470k C=100n; fbclip Rg=4.7k Cg=47n Rf=10k+pot(2,470k,A) Cf=51p d=si up=1 dn=1 rail=4.2; tonebm R1=22k C1=10n R2=22k C2=4n t=taper(0,B); vol a=taper(1,A)"),
          "Overdrive 'classico' a operazionale (famiglia Tube Screamer, stima) con medi bilanciati e piu' guadagno: buffer, stadio a op-amp con diodi in controreazione, tone, uscita a bassa impedenza (stima: struttura TS). Parte funzionale provvisoria (segnaposto) finche' non arriva la scheda sonora."),

    # MXR YJM308 Yngwie Malmsteen Overdrive - 2024
    stomp("yjm308", "YO-7", "Neoclassic Drive", "MXR YJM308 Yngwie Malmsteen Overdrive",
          ("YJM308", "Overdrive"), "Overdrive / Boost", (196, 32, 36),
          look("mxr", (61, 111, 36),
               [('LEVEL', 24, 22, 'knob'), ('GAIN', 76, 22, 'knob')],
               feet=[('ON/OFF', 50, 82)], leds=[(50, 14, 'blue')], extra=[], finish='paint', gfx={'panels': [('rect', 5, 3, 95, 97, None, (232, 230, 222), 2.5, 0.5)],
                'name': {'col': (232, 230, 222), 'font': 'script', 'upper': False, 'y': 50.4, 'size': 5.5},
                'label': {'col': (232, 230, 222)},
                'code': {'size': 2.6, 'col': (232, 230, 222)}}),
          ("Circuit", [knob("LEVEL", "level"),
            knob("GAIN", "gain")],
           "hpf R=470k C=100n; fbclip Rg=4.7k Cg=47n Rf=10k+pot(1,470k,A) Cf=51p d=si up=1 dn=1 rail=4.2; lpf R=10k C=4.7n; vol a=taper(0,A)"),
          "Overdrive a 2 comandi della famiglia Distortion+/DOD 250 (stima: erede del DOD YJM308): stadio non invertente a op-amp con diodi verso massa e volume passivo (stima: famiglia DOD 250/YJM308 di DOD, cfr. Parte funzionale provvisoria (segnaposto) finche' non arriva la scheda sonora."),

    # MXR RR104 Randy Rhoads Distortion+ - 2024 (manuale agosto 2024)
    stomp("rr104", "YD-3", "Concorde Plus", "MXR RR104 Randy Rhoads Distortion+",
          ("RR104", "Distortion+"), "Distorsione", (238, 200, 40),
          look("mxr", (61, 111, 36),
               [('OUTPUT', 24, 22, 'knob'), ('DISTORTION', 76, 22, 'knob')],
               feet=[('ON/OFF', 50, 82)], leds=[(50, 14, 'red')], extra=[], finish='paint', gfx={'panels': [],
                'name': {'col': (24, 24, 26), 'font': 'black', 'upper': True, 'y': 50.4, 'size': 5.5},
                'label': {'col': (24, 24, 26)},
                'name_deco': {'style': 'lines', 'col': (24, 24, 26), 'pad': 2.0},
                'code': {'size': 2.6, 'col': (24, 24, 26)}}),
          ("Circuit", [knob("OUTPUT", "level"),
            knob("DISTORTION", "gain")],
           "hpf R=470k C=100n; opni Rg=2.2k Cg=1u Rf=10k+pot(1,470k,A) Cf=100p rail=4; dclip R=2.2k C=10n d=si; lpf R=10k C=4.7n; vol a=taper(0,A)"),
          "Distortion+ (op-amp + diodi al germanio verso massa) tarato sull'esemplare dell'artista: op-amp non invertente (guadagno = 1 + 1 MOhm / (4,7 kOhm + pot)), diodi al germanio verso massa, volume passivo. Parte funzionale provvisoria (segnaposto) finche' non arriva la scheda sonora."),

    # MXR EVH30 EVH 5150 Chorus - 2018 (novembre)
    stomp("evh30", "YC-2", "Striped Chorus", "MXR EVH30 EVH 5150 Chorus",
          ("EVH30", "5150 Chorus"), "Chorus / Dimension", (236, 228, 206),
          look("mxr_big", (92, 121, 38),
               [('VOLUME', 20, 20, 'knob'), ('TONE', 50, 20, 'knob'), ('INTENSITY', 80, 20, 'knob'),
                ('INPUT', 30, 46, 'lever', ['INPUT LEVEL']), ('OUTPUT', 70, 46, 'lever', ['OUTPUT LEVEL'])],
               feet=[('ON/OFF', 50, 84)], leds=[(66.8, 84, 'blue')], extra=[], finish='paint', gfx={'panels': [('stripes', (40, 80, 170), 3.0, 13.0, 28)],
                'name': {'col': (232, 230, 222), 'font': 'black', 'upper': True, 'y': 60.7, 'size': 6.5},
                'label': {'col': (24, 24, 26)},
                'name_deco': {'style': 'box', 'col': (40, 80, 170), 'pad': 2.0},
                'code': {'size': 2.6, 'col': (24, 24, 26)}}),
          ("BBDChorus", [knob("VOLUME", "level"),
            knob("TONE", "level"),
            knob("INTENSITY", "depth"),
            selector("INPUT", "level", ['-20 DB', '-35 DB', '-50 DB'], 0, short=['-20D', '-35D', '-50D']),
            toggle("OUTPUT", "level", ("-20 DB", "-35 DB"), 0)],
           "type=chorus stages=1024 clk=85000,150000 rate=0.32,3.5 lfo=0 aa=6800 comp=0 sat=1"),
          "Chorus analogico ispirato al Roland DC-30 (un solo comando di intensita'), stereo, con attenuatori di livello: attenuatore d'ingresso commutabile, linea BBD con LFO (intensita' unica come i Roland CE-1/DC-30), tone, attenuatore d'uscita, uscite mono/stereo (dry e wet separati, stima). Parte funzionale provvisoria (segnaposto) finche' non arriva la scheda sonora.", stereo=True),
]
