.TH PEDAL-TRINITY 1 "2026-09-29" "1.1.2 beta" "Pedal Trinity"
.SH NAME
pedal-trinity \- guitar pedalboard with 220 emulated stompboxes (standalone)
.SH SYNOPSIS
.B pedal-trinity
[\fB\-\-selftest\fR] [\fB\-\-version\fR] [\fB\-\-screenshot\fR \fIfile.png\fR [\fB\-\-scale\fR \fIn\fR] [\fB\-\-info\fR] [\fB\-\-set\fR \fIid=value\fR]...]
.SH DESCRIPTION
Pedal Trinity is a pedalboard of up to 100 slots chosen from a catalogue of
220 original stompbox models (drive, modulation, delay, reverb, pitch, dynamics,
EQ, amp simulators, cabinet IRs, A/B splitters), with factory and user presets.
The same effect is installed as VST3 (/usr/lib/vst3) and LV2 (/usr/lib/lv2) plugin.
Audio devices (ALSA or JACK) are selected from the Options menu.
.SH OPTIONS
.TP
.B \-\-selftest
run the automatic DSP tests and exit (exit status 0 on success).
.TP
.B \-\-version
print the version.
.TP
.BI \-\-screenshot " file.png"
save an image of the user interface and exit.
.SH FILES
/usr/share/doc/pedal-trinity/PedalTrinity_Guida.pdf \- illustrated guide (Italian).
.SH AUTHOR
FabioNET. Licensed under the GNU General Public License v3 or later.
